# Generated by Django 5.0.14 on 2025-10-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(upload_to="images"),
        ),
    ]
